spring:
  application:
    name: mimg-ibge
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mimg-ibge
    res:
      defaultMediaType: application/json
  server:
    port: 5000