spring:
  application:
    name: mimg-ibge
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mimg-ibge
    res:
      defaultMediaType: application/json

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

swagger:
  version: 1.0
  description : APIs - Módulo de Informações Municipais Georreferenciadas